[package]
name = "executor"
version.workspace = true
edition.workspace = true
license.workspace = true
[lib]
crate-type = ["cdylib", "rlib"]
[[example]]
name = "executor-export"
path = "examples/export.rs"
[dependencies]
ic-laya-core.workspace = true
canister-common.workspace = true
ic-cdk.workspace = true
candid.workspace = true
serde.workspace = true
serde_json.workspace = true
bincode.workspace = true
ic-stable-structures.workspace = true
