[package]
name = "verdict-candle"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
ic-laya-core.workspace = true
laya-candle.workspace = true
hf-tokenizer.workspace = true
candle-core.workspace = true
serde.workspace = true
serde_json.workspace = true

[[bin]]
name = "verdict-infer"
path = "src/bin/verdict_infer.rs"
