;; Test-only caller: forwards raw Candid with cycles, and records the IC refund.
;; Request: target_len:u32, method_len:u32, cycles:u64, target, method, candid.
(module
  (import "ic0" "msg_arg_data_size" (func $size (result i32)))
  (import "ic0" "msg_arg_data_copy" (func $copy (param i32 i32 i32)))
  (import "ic0" "msg_reply_data_append" (func $append (param i32 i32)))
  (import "ic0" "msg_reply" (func $reply))
  (import "ic0" "msg_reject" (func $reject (param i32 i32)))
  (import "ic0" "msg_cycles_refunded128" (func $refunded (param i32)))
  (import "ic0" "call_new" (func $new (param i32 i32 i32 i32 i32 i32 i32 i32)))
  (import "ic0" "call_data_append" (func $data (param i32 i32)))
  (import "ic0" "call_cycles_add128" (func $cycles (param i64 i64)))
  (import "ic0" "call_perform" (func $perform (result i32)))
  (memory (export "memory") 40)
  (table 2 funcref)
  (elem (i32.const 0) $ok $err)
  (func $ok (param i32)
    (call $refunded (i32.const 0))
    (call $copy (i32.const 128) (i32.const 0) (call $size))
    (call $append (i32.const 128) (call $size))
    (call $reply))
  (func $err (param i32)
    (call $refunded (i32.const 0))
    (call $reject (i32.const 0) (i32.const 0)))
  (func (export "canister_query refund")
    (call $append (i32.const 0) (i32.const 16)) (call $reply))
  (func (export "canister_update forward") (local $target i32) (local $method i32) (local $args i32)
    (call $copy (i32.const 128) (i32.const 0) (call $size))
    (local.set $target (i32.load (i32.const 128)))
    (local.set $method (i32.load (i32.const 132)))
    (local.set $args (i32.add (i32.const 144) (i32.add (local.get $target) (local.get $method))))
    (call $new (i32.const 144) (local.get $target)
      (i32.add (i32.const 144) (local.get $target)) (local.get $method)
      (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 0))
    (call $data (local.get $args) (i32.sub (call $size) (i32.sub (local.get $args) (i32.const 128))))
    (call $cycles (i64.const 0) (i64.load (i32.const 136)))
    (if (call $perform) (then unreachable)))
)
