import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {connectQuery,type QueryClient,type Game,type Decision,type Pose} from './placement-query-api';
import {rotations,sequence} from './game';
import './style.css';
import './placement.css';
const colors=['#0c1510','#46d5ed','#efd55a','#b697ff','#65df99','#f48392','#639bff','#f9b367'];
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
const label=(p:Pose)=>`${['No rotation','Rotate right','Rotate 180°','Rotate left'][p.r]} · column ${p.x+1}`;
function App(){
 const [client,setClient]=useState<QueryClient>();
 const [game,setGame]=useState<Game>();const [receipt,setReceipt]=useState<Decision>();const [board,setBoard]=useState<number[]>(Array(200).fill(0));
 const [ghost,setGhost]=useState<[number,number][]>([]);const [moving,setMoving]=useState<[number,number][]>([]);
 const [busy,setBusy]=useState(false);const [auto,setAuto]=useState(false);const running=useRef(false);
 const [error,setError]=useState('');const [elapsed,setElapsed]=useState(0);
 const [seed,setSeed]=useState(184);const [mode,setMode]=useState(0);
 const host=import.meta.env.VITE_IC_HOST||'https://icp-api.io';const canister=import.meta.env.VITE_CANISTER_ID||'';
 useEffect(()=>{let live=true;connectQuery(host,canister).then(c=>{if(live)setClient(c);}).catch(e=>setError(String(e)));return()=>{live=false;};},[]);
 const start=async()=>{if(!client)return;setBusy(true);setError('');setAuto(false);try{if(mode===0&&!(await client.status()).enabled)throw new Error('Model unavailable or query token limit too low');const g=client.start(seed>>>0,mode);setGame(g);setBoard(g.board);setReceipt(undefined);setGhost([]);setMoving([]);setAuto(true);}catch(e){setError(String(e));}finally{setBusy(false);}};
 const step=async()=>{if(!client||!game||busy||running.current||game.over)return;running.current=true;setBusy(true);setError('');try{
 const begin=performance.now();const r=await client.step(game);setElapsed(performance.now()-begin);setReceipt(r);setBoard(r.before);setGhost(r.candidates[r.selected].cells);await sleep(650);
 for(const p of r.candidates[r.selected].path){setMoving(rotations(r.piece)[p.r].map(([x,y])=>[x+p.x,y+p.y]));await sleep(35);}
 setMoving([]);setGhost([]);setBoard(r.after);setGame({...game,board:r.after,turn:r.turn+1,lines:r.total_lines,over:r.over});
 }catch(e){setError(String(e));setAuto(false);}finally{running.current=false;setBusy(false);}};
 useEffect(()=>{if(!auto||busy||!game||game.over)return;const timer=setTimeout(()=>{if(document.hidden){setAuto(false);return;}void step();},600);return()=>clearTimeout(timer);},[auto,busy,game]);
 const saveReply=()=>{if(!receipt)return;const blob=new Blob([JSON.stringify({host,canister,model_request:receipt.model_request,local_input:{board:receipt.before,seed:game?.seed,turn:receipt.turn},response:receipt,certified:false},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`tetris-query-turn-${receipt.turn+1}.json`;a.click();URL.revokeObjectURL(a.href);};
 const nextPiece=sequence(game?.seed??seed,(game?.turn??0)+1)[game?.turn??0];
 return <main><header><a className="brand" href="/">open<span>Jev</span><small>ARCADE</small></a><span className="network"><i/>{client?.local?'LOCAL CANISTER':'ICP CANISTER'}</span></header>
 <div className="demo-layout"><section className="arcade"><div className="title"><p>ON-CANISTER INFERENCE / 151M</p><h1>One more <em>block.</em></h1><span>A 151M model picks each placement inside an ICP canister.</span></div>
 <div className="cabinet"><div className="playfield"><div className="board-heading"><span>TETRIS / {game?.mode===1?'HEURISTIC':'151M MODEL'}</span><span className="phase">{busy?'DECIDING':game?.over?'COMPLETE':game?'READY':'STANDBY'}</span></div><div className="board-frame"><svg viewBox="0 0 240 480" className="board" role="img" aria-label="Tetris board">{board.map((v,i)=><rect key={i} x={i%10*24+1} y={Math.floor(i/10)*24+1} width="22" height="22" rx="2" fill={colors[v]}/>)}{ghost.map(([x,y],i)=><rect className="ghost" key={`g${i}`} x={x*24+2} y={y*24+2} width="20" height="20" fill="none" stroke="#c7ed87" strokeWidth="2"/>)}{moving.map(([x,y],i)=><rect className="active-piece" key={`m${i}`} x={x*24+1} y={y*24+1} width="22" height="22" rx="2" fill={colors[(receipt?.piece??0)+1]}/>)}</svg>{!game&&<div className="overlay"><span>151M / ON ICP</span><strong>One more<br/>block.</strong><small>A small model. One more move.</small></div>}</div></div>
 <aside><div className="next"><h2>NEXT</h2>{game?<svg viewBox="0 0 100 60" aria-label="Next piece">{rotations(nextPiece)[0].map(([x,y],i)=><rect key={i} x={x*20+5} y={y*20+5} width="18" height="18" rx="2" fill={colors[nextPiece+1]}/>)}</svg>:<div className="next-empty">—</div>}</div><div className="stats"><h2>LINES</h2><strong>{String(game?.lines||0).padStart(2,'0')}</strong><h2>TURNS</h2><strong>{String(game?.turn||0).padStart(2,'0')}</strong></div><div className="chip">151M<small>PARAMETERS<br/>RUNNING ON ICP</small></div></aside></div>
 <button className="start" disabled={(busy&&!auto)||!client} onClick={!game||game.over?start:()=>setAuto(!auto)}>{!game||game.over?'Start game':auto?'Pause':'Resume'}<span>{auto?'Ⅱ':'→'}</span></button>
 {game&&<div className="play-actions"><button disabled={busy||game.over||auto} onClick={()=>void step()}>Step once</button><button disabled={busy} onClick={start}>New game</button></div>}
 <p className="status">{busy?'Choosing a placement and playing the move…':game?.over?'Run complete (up to 128 turns).':game?'Ready for the next move.':'Your browser builds candidates. The canister model chooses. Query calls only.'}</p><p className="caption">Placement-based play · Board state stays in your browser</p>
 {error&&<p role="alert" className="fault">{error}</p>}
 <details className="settings"><summary>Comparison mode & seed</summary><div className="controls"><label>Policy <select value={mode} disabled={busy} onChange={e=>setMode(Number(e.target.value))}><option value={0}>151M model</option><option value={1}>Heuristic only (no model)</option></select></label><label>Piece sequence seed <input type="number" value={seed} disabled={busy} onChange={e=>setSeed(Number(e.target.value))}/></label></div><p>Settings apply to the next game.</p></details></section>

 <section className="decision"><div className="decision-heading"><h2>This decision</h2><span>MODEL ON CANISTER</span></div>{receipt?<><dl className="turn-details"><dt>Candidates</dt><dd>{receipt.candidates.length} offered <small>/ {receipt.legal_count} legal placements</small></dd><dt>Heuristic recommendation</dt><dd>{label(receipt.candidates[receipt.recommended].pose)}</dd><dt>{receipt.mode===0?'151M choice':'Heuristic choice'}</dt><dd className="chosen">{label(receipt.candidates[receipt.selected].pose)}</dd><dt>Decision time</dt><dd>{(elapsed/1000).toFixed(2)} s <small>{receipt.mode===0?'including network time':'local computation'}</small></dd><dt>Model instructions / input</dt><dd>{Number(receipt.inference_instructions).toLocaleString("en-US")} / {receipt.input_tokens} tokens</dd><dt>Inference</dt><dd>{receipt.rounds.length} model pass / {receipt.query_count} query</dd><dt>Response log</dt><dd>Turn {receipt.turn+1} <button onClick={saveReply}>Save input / output JSON</button></dd></dl><details><summary>Inspect candidates & features</summary><table><thead><tr><th>Choice</th><th>Lines</th><th>Holes</th><th>Height</th><th>Score</th></tr></thead><tbody>{receipt.candidates.map((c,i)=><tr key={i} className={i===receipt.selected?'selected':''}><td>{i+1}{i===receipt.selected?' ●':''}{i===receipt.recommended?' ★':''}</td><td>{c.lines}</td><td>{c.holes}</td><td>{c.height}</td><td>{c.evaluation}</td></tr>)}</tbody></table><p>● Selected · ★ Heuristic recommendation</p>{receipt.rounds.map((r,i)=><p key={i}>Pass {i+1}: candidates {r.model_candidates.map(n=>n+1).join(", ")} → {r.selected+1} ({r.input_tokens} tokens)</p>)}<pre>{receipt.prompt||'No model call'}</pre></details></>:<p>Start a game to compare the candidates and the model’s choice.</p>}
 <details className="note"><summary>What the code and model do</summary><p>Your browser computes legal placements, groups identical line/holes/height outcomes, and offers up to four different outcomes by feature distance. It does not use the heuristic score to pick candidates.</p><p>The heuristic compares the same candidates using 10 × cleared lines − 8 × holes − height. Browser code converts cleared lines to a shortfall from the most lines any offered candidate clears. It describes holes, height, and this shortfall as min, mid, max, or equal; lower is better for each. In one query, the 151M model reads these descriptions and chooses a placement. The combined heuristic score is not sent to the model.</p><p>Comparison mode uses the same seeded piece sequence without calling the model or canister.</p></details></section></div>
 <details className="about"><summary>About queries & response logs</summary><p>Your browser computes legal placements, features, and the next board. It sends only short candidate descriptions to the canister's general model query. Comparison mode makes no decision query. Board state and logs stay in your browser. Exported JSON is a local input/output log, not a certificate of a consensus-backed, persistent decision.<br/>Canister: {canister||'not configured'} / {host}</p></details><footer>151M PARAMETERS · INTERNET COMPUTER</footer></main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
